CREATE TABLE `ancen_artbrut_cate` (
  `ancen_artbrut_cate_sn` smallint(5) unsigned NOT NULL auto_increment COMMENT '分類編號',
  `ancen_artbrut_cate_parent_sn` smallint(5) unsigned NOT NULL COMMENT '父分類',
  `ancen_artbrut_cate_title` varchar(255) NOT NULL COMMENT '分類標題',
  `ancen_artbrut_cate_desc` varchar(255) NOT NULL COMMENT '分類說明',
  `ancen_artbrut_cate_sort` smallint(5) unsigned NOT NULL COMMENT '分類排序',
  `ancen_artbrut_cate_enable` enum('1','0') NOT NULL default '1' COMMENT '狀態',
  PRIMARY KEY  (`ancen_artbrut_cate_sn`)
) ENGINE=MyISAM;


CREATE TABLE `ancen_artbrut_photo` (
  `ancen_artbrut_photo_sn` int(11) NOT NULL COMMENT '流水號',
  `ancen_artbrut_photo_category` int(11) NOT NULL COMMENT '分類',
  `ancen_artbrut_photo_item_title_en` varchar(255) DEFAULT NULL COMMENT '作品名稱(英)',
  `ancen_artbrut_photo_item_title_tw` varchar(255) DEFAULT NULL COMMENT '作品名稱(中)',
  `ancen_artbrut_photo_size` varchar(255) DEFAULT NULL COMMENT '尺寸：長x寬 cm',
  `ancen_artbrut_photo_3dname` varchar(255) DEFAULT NULL COMMENT '3D檔名',
  `ancen_artbrut_photo_diginame` varchar(255) DEFAULT NULL COMMENT '數位檔名',
  `ancen_artbrut_photo_resource` varchar(255) DEFAULT NULL COMMENT '資料識別',
  `ancen_artbrut_photo_record` varchar(255) DEFAULT NULL COMMENT '盤點紀錄',
  `ancen_artbrut_photo_photographer_en` varchar(255) DEFAULT NULL COMMENT '拍攝者(英)',
  `ancen_artbrut_photo_photographer_tw` varchar(255) DEFAULT NULL COMMENT '拍攝者(中)',
  `ancen_artbrut_photo_coveragr_en` varchar(255) DEFAULT NULL COMMENT '收藏處(英)',
  `ancen_artbrut_photo_coveragr_tw` varchar(255) DEFAULT NULL COMMENT '收藏處(中)',
  `ancen_artbrut_photo_description_en` longtext DEFAULT NULL COMMENT '描述(英)',
  `ancen_artbrut_photo_description_tw` longtext DEFAULT NULL COMMENT '描述(中)',
  `ancen_artbrut_photo_year` varchar(255) DEFAULT NULL COMMENT '年代',
  `ancen_artbrut_photo_keywords_en` varchar(255) DEFAULT NULL COMMENT '主題和關鍵字(英)',
  `ancen_artbrut_photo_keywords_tw` varchar(255) DEFAULT NULL COMMENT '主題和關鍵字(中)',
  `ancen_artbrut_photo_creator_en` varchar(255) DEFAULT NULL COMMENT '創作者(英)',
  `ancen_artbrut_photo_creator_tw` varchar(255) DEFAULT NULL COMMENT '創作者(中)',
  `ancen_artbrut_photo_resourcetype_en` varchar(255) DEFAULT NULL COMMENT '資料型態(英)',
  `ancen_artbrut_photo_resourcetype_tw` varchar(255) DEFAULT NULL COMMENT '資料型態(中)',
  `ancen_artbrut_photo_owner_en` varchar(255) DEFAULT NULL COMMENT '收藏者(英)',
  `ancen_artbrut_photo_owner_tw` varchar(255) DEFAULT NULL COMMENT '收藏者(中)',
  `ancen_artbrut_photo_publisher_en` varchar(255) DEFAULT NULL COMMENT '出版者(英)',
  `ancen_artbrut_photo_publisher_tw` varchar(255) DEFAULT NULL COMMENT '出版者(中)',
  `ancen_artbrut_photo_contributor_en` varchar(255) DEFAULT NULL COMMENT '貢獻者(英)',
  `ancen_artbrut_photo_contributor_tw` varchar(255) DEFAULT NULL COMMENT '貢獻者(中)',
  `ancen_artbrut_photo_language_en` varchar(255) DEFAULT NULL COMMENT '語言(英)',
  `ancen_artbrut_photo_language_tw` varchar(255) DEFAULT NULL COMMENT '語言(中)',
  `ancen_artbrut_photo_relation_en` varchar(255) DEFAULT NULL COMMENT '資料來源(英)',
  `ancen_artbrut_photo_relation_tw` varchar(255) DEFAULT NULL COMMENT '資料來源(中)',
  `ancen_artbrut_photo_o_right_en` varchar(255) DEFAULT NULL COMMENT '原始物件典藏單位(英)',
  `ancen_artbrut_photo_o_right_tw` varchar(255) DEFAULT NULL COMMENT '原始物件典藏單位(中)',
  `ancen_artbrut_photo_d_right_en` varchar(255) DEFAULT NULL COMMENT '數位化後物件典藏單位(英)',
  `ancen_artbrut_photo_d_right_tw` varchar(255) DEFAULT NULL COMMENT '數位化後物件典藏單位(中)',
  `ancen_artbrut_photo_metadata_en` varchar(255) DEFAULT NULL COMMENT '後設資料著錄單位(英)',
  `ancen_artbrut_photo_metadata_tw` varchar(255) DEFAULT NULL COMMENT '後設資料著錄單位(中)',
  `ancen_artbrut_photo_memo_en` varchar(255) DEFAULT NULL COMMENT '備註(英)',
  `ancen_artbrut_photo_memo_tw` varchar(255) DEFAULT NULL COMMENT '備註(中)',
  PRIMARY KEY  (`ancen_artbrut_photo_sn`)
) ENGINE=MyISAM;

